#!/usr/bin/env bash
#
# Student-PA One-Line Installer
# Usage: curl -fsSL https://your-domain.com/install.sh | bash
#        curl -fsSL https://your-domain.com/install.sh | bash -s -- --non-interactive
#

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Config
INSTALL_DIR="${HOME}/student-pa"
IMAGE_NAME="ghcr.io/abenable/student-pa:latest"
CONTAINER_NAME="student-pa"

echo -e "${BLUE}=========================================${NC}"
echo -e "${BLUE}  Student-PA Installer${NC}"
echo -e "${BLUE}  Hermes Agent for Students${NC}"
echo -e "${BLUE}=========================================${NC}"
echo ""

# ─── Check Prerequisites ──────────────────────────────────────────

check_command() {
    if ! command -v "$1" &> /dev/null; then
        echo -e "${RED}✗ $1 is not installed.${NC}"
        return 1
    fi
    echo -e "${GREEN}✓ $1 found${NC}"
}

echo -e "${BLUE}Checking prerequisites...${NC}"

MISSING_DEPS=0
check_command "docker" || MISSING_DEPS=1
check_command "curl" || MISSING_DEPS=1

if [ "$MISSING_DEPS" -eq 1 ]; then
    echo ""
    echo -e "${RED}Please install the missing dependencies and re-run this script.${NC}"
    echo "  Docker: https://docs.docker.com/get-docker/"
    echo "  curl:   sudo apt-get install curl   (Debian/Ubuntu)"
    echo "          sudo yum install curl       (RHEL/CentOS)"
    echo "          brew install curl           (macOS)"
    exit 1
fi

# Check Docker daemon is running
if ! docker info &> /dev/null; then
    echo -e "${RED}✗ Docker daemon is not running.${NC}"
    echo "   Start Docker:  sudo systemctl start docker"
    exit 1
fi

echo ""

# ─── Collect Configuration ────────────────────────────────────────

# Support non-interactive mode via environment variables
if [ "${1:-}" = "--non-interactive" ] || [ "${NON_INTERACTIVE:-}" = "true" ]; then
    NON_INT=true
else
    NON_INT=false
fi

prompt_or_env() {
    local var_name="$1"
    local prompt_text="$2"
    local is_secret="${3:-false}"
    local value=""

    # Check if already set in environment
    eval "value=\"\${$var_name:-}\""

    if [ -n "$value" ]; then
        echo -e "${GREEN}✓ $var_name is set from environment${NC}"
        return
    fi

    if [ "$NON_INT" = true ]; then
        echo -e "${RED}✗ $var_name is required but not set.${NC}"
        echo "   Set it via environment variable: export $var_name=..."
        exit 1
    fi

    echo -n "$prompt_text: "
    if [ "$is_secret" = true ]; then
        read -rs value
        echo ""
    else
        read -r value
    fi

    if [ -z "$value" ]; then
        echo -e "${YELLOW}⚠ $var_name is empty. Some features may not work.${NC}"
    fi

    eval "export $var_name=\"$value\""
}

echo -e "${BLUE}Configuring Student-PA...${NC}"
echo "   LiteLLM endpoint: http://host.docker.internal:4000/v1"
echo "   (Set LITELLM_API_KEY as env var to skip the prompt)"
echo ""

prompt_or_env "LITELLM_API_KEY" "LiteLLM API Key" "true"
prompt_or_env "TELEGRAM_BOT_TOKEN" "Telegram Bot Token (optional, press Enter to skip)" "false"

# ─── Setup Directory & Config ─────────────────────────────────────

echo ""
echo -e "${BLUE}Setting up installation directory...${NC}"

mkdir -p "$INSTALL_DIR"/{hermes-data,student-data,services}
cd "$INSTALL_DIR"

# Write .env file
cat > .env <<EOF
# Student-PA Environment Configuration
# Generated by installer on $(date -Iseconds)

# LiteLLM Gateway (hardcoded — container reaches host via Docker DNS)
LITELLM_API_BASE=http://host.docker.internal:4000/v1
LITELLM_API_KEY=${LITELLM_API_KEY:-}

# Telegram Gateway (optional)
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}

# Hermes configuration
HERMES_HOME=/home/hermes/.hermes
EOF

# Write minimal docker-compose.yml
cat > docker-compose.yml <<'EOF'
version: "3.8"

services:
  student-pa:
    image: ghcr.io/abenable/student-pa:latest
    container_name: student-pa
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./hermes-data:/home/hermes/.hermes
      - ./student-data:/home/hermes/student-data
      - ./services:/app/services
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stdin_open: true
    tty: true
EOF

echo -e "${GREEN}✓ Configuration written to $INSTALL_DIR/.env${NC}"

# ─── Pull & Run ───────────────────────────────────────────────────

echo ""
echo -e "${BLUE}Pulling Student-PA image...${NC}"

if ! docker pull "$IMAGE_NAME" 2>/dev/null; then
    echo -e "${YELLOW}⚠ Could not pull $IMAGE_NAME${NC}"
    echo "   The image may be private or not yet published."
    echo ""
    echo "   To build locally from source:"
    echo "     git clone https://github.com/abenable/student-pa.git"
    echo "     cd student-pa && docker compose up -d --build"
    echo ""
    echo "   To use a custom image:"
    echo "     export STUDENT_PA_IMAGE=your-image:tag"
    echo "     curl ... | bash"
    exit 1
fi

echo -e "${GREEN}✓ Image pulled${NC}"
echo ""
echo -e "${BLUE}Starting Student-PA container...${NC}"

docker compose up -d

echo ""
echo -e "${GREEN}=========================================${NC}"
echo -e "${GREEN}  Student-PA is running!${NC}"
echo -e "${GREEN}=========================================${NC}"
echo ""
echo "  Container:  $CONTAINER_NAME"
echo "  Directory:  $INSTALL_DIR"
echo ""
echo "Quick commands:"
echo "  docker logs -f $CONTAINER_NAME        # View logs"
echo "  docker exec -it $CONTAINER_NAME hermes setup   # First-time setup"
echo "  docker exec -it $CONTAINER_NAME hermes         # Interactive chat"
echo "  docker exec -it $CONTAINER_NAME hermes -z \"Your prompt\"  # One-shot"
echo ""

if [ -n "${TELEGRAM_BOT_TOKEN:-}" ]; then
    echo "Telegram gateway:"
    echo "  docker exec -d $CONTAINER_NAME hermes gateway run"
    echo ""
fi

echo -e "${YELLOW}Next steps:${NC}"
echo "  1. Run first-time setup:  docker exec -it $CONTAINER_NAME hermes setup"
echo "  2. Configure your model:  docker exec -it $CONTAINER_NAME hermes model"
if [ -n "${TELEGRAM_BOT_TOKEN:-}" ]; then
    echo "  3. Start Telegram bot:    docker exec -d $CONTAINER_NAME hermes gateway run"
fi
echo ""
