#!/usr/bin/env bash
#
# Student-PA One-Line Installer
# Usage: curl -fsSL https://raw.githubusercontent.com/abenable/student-pa/main/install.sh | bash
#        curl -fsSL ... | bash -s -- --non-interactive
#

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Config
INSTALL_DIR="${HOME}/student-pa"
IMAGE_NAME="ghcr.io/abenable/student-pa:latest"
CONTAINER_NAME="student-pa-agent"

# Docker Compose detection
if docker compose version &>/dev/null; then
    COMPOSE_CMD="docker compose"
elif docker-compose version &>/dev/null; then
    COMPOSE_CMD="docker-compose"
else
    COMPOSE_CMD=""
fi

echo -e "${BLUE}=========================================${NC}"
echo -e "${BLUE}  Student-PA Installer${NC}"
echo -e "${BLUE}  Hermes Agent for Students${NC}"
echo -e "${BLUE}=========================================${NC}"
echo ""

# ─── Check Prerequisites ──────────────────────────────────────────

check_command() {
    if ! command -v "$1" &> /dev/null; then
        echo -e "${RED}✗ $1 is not installed.${NC}"
        return 1
    fi
    echo -e "${GREEN}✓ $1 found${NC}"
}

echo -e "${BLUE}Checking prerequisites...${NC}"

MISSING_DEPS=0
check_command "docker" || MISSING_DEPS=1
check_command "curl" || MISSING_DEPS=1

if [ -z "$COMPOSE_CMD" ]; then
    echo -e "${RED}✗ Docker Compose is not installed.${NC}"
    MISSING_DEPS=1
else
    echo -e "${GREEN}✓ Docker Compose found ($COMPOSE_CMD)${NC}"
fi

if [ "$MISSING_DEPS" -eq 1 ]; then
    echo ""
    echo -e "${RED}Please install the missing dependencies and re-run.${NC}"
    echo "  Docker:        https://docs.docker.com/get-docker/"
    echo "  Docker Compose: sudo apt-get install docker-compose-plugin"
    exit 1
fi

if ! docker info &> /dev/null; then
    echo -e "${RED}✗ Docker daemon is not running.${NC}"
    echo "   Start Docker:  sudo systemctl start docker"
    exit 1
fi

echo ""

# ─── Collect Configuration ────────────────────────────────────────

NON_INT=false
if [ "${1:-}" = "--non-interactive" ] || [ "${NON_INTERACTIVE:-}" = "true" ]; then
    NON_INT=true
fi

prompt_or_env() {
    local var_name="$1"
    local prompt_text="$2"
    local is_secret="${3:-false}"
    local value=""

    eval "value=\"\${$var_name:-}\""

    if [ -n "$value" ]; then
        echo -e "${GREEN}✓ $var_name is set from environment${NC}"
        return
    fi

    if [ "$NON_INT" = true ]; then
        echo -e "${RED}✗ $var_name is required but not set.${NC}"
        echo "   Set it via environment variable: export $var_name=..."
        exit 1
    fi

    echo -n "$prompt_text: "
    if [ "$is_secret" = true ]; then
        read -rs value
        echo ""
    else
        read -r value
    fi

    if [ -z "$value" ]; then
        echo -e "${YELLOW}⚠ $var_name is empty. Some features may not work.${NC}"
    fi

    eval "export $var_name=\"$value\""
}

echo -e "${BLUE}Configuring Student-PA...${NC}"
echo "   LiteLLM endpoint: http://host.docker.internal:4000/v1"
echo "   (Set LITELLM_API_KEY as env var to skip the prompt)"
echo ""

prompt_or_env "LITELLM_API_KEY" "LiteLLM API Key" "true"
prompt_or_env "TELEGRAM_BOT_TOKEN" "Telegram Bot Token (optional, press Enter to skip)" "false"

# ─── Setup Directory & Config ─────────────────────────────────────

echo ""
echo -e "${BLUE}Setting up installation directory...${NC}"

mkdir -p "$INSTALL_DIR"/{hermes-data,student-data,services,gws-auth}
cd "$INSTALL_DIR"

cat > .env <<EOF
# Student-PA Environment Configuration
# Generated by installer on $(date -Iseconds)

# LiteLLM Gateway (hardcoded — container reaches host via Docker DNS)
LITELLM_API_BASE=http://host.docker.internal:4000
LITELLM_API_KEY=${LITELLM_API_KEY:-}
DEFAULT_MODEL=gemini-1.5-pro

# Telegram Gateway (optional)
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
TELEGRAM_ALLOWED_USERS=${TELEGRAM_ALLOWED_USERS:-}
TELEGRAM_HOME_CHANNEL=${TELEGRAM_HOME_CHANNEL:-}

# Hermes configuration
HERMES_HOME=/home/hermes/.hermes
EOF

# Write docker-compose.yml that matches the repo exactly
cat > docker-compose.yml <<'EOF'
services:
  agent:
    image: ghcr.io/abenable/student-pa:latest
    container_name: student-pa-agent
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - LITELLM_API_BASE=${LITELLM_API_BASE:-http://host.docker.internal:4000}
      - LITELLM_API_KEY=${LITELLM_API_KEY:-}
      - DEFAULT_MODEL=${DEFAULT_MODEL:-gemini-1.5-pro}
      - HERMES_HOME=/home/hermes/.hermes
      - HERMES_INFERENCE_PROVIDER=openai
      - OPENAI_API_KEY=${LITELLM_API_KEY:-}
      - OPENAI_BASE_URL=${LITELLM_API_BASE:-http://host.docker.internal:4000}/v1
      - HERMES_MODEL=${DEFAULT_MODEL:-gemini-1.5-pro}
      - GOOGLE_WORKSPACE_CLI_CONFIG_DIR=/home/hermes/.gws
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
      - TELEGRAM_ALLOWED_USERS=${TELEGRAM_ALLOWED_USERS:-}
      - TELEGRAM_HOME_CHANNEL=${TELEGRAM_HOME_CHANNEL:-}
    volumes:
      - ./hermes-data:/home/hermes/.hermes
      - ./services:/app/services:ro
      - ./student-data:/home/hermes/student-data
      - ./gws-auth:/home/hermes/.gws
    extra_hosts:
      - "host.docker.internal:host-gateway"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - DAC_OVERRIDE
      - CHOWN
      - FOWNER
    healthcheck:
      test: ["CMD", "python3", "-c", "import hermes_agent"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
EOF

echo -e "${GREEN}✓ Configuration written to $INSTALL_DIR/.env${NC}"

# ─── Pull & Run ───────────────────────────────────────────────────

echo ""
echo -e "${BLUE}Pulling Student-PA image...${NC}"

if ! docker pull "$IMAGE_NAME" 2>/dev/null; then
    echo -e "${YELLOW}⚠ Could not pull $IMAGE_NAME${NC}"
    echo "   The image may be private or not yet published."
    echo ""
    echo "   To build locally from source:"
    echo "     git clone https://github.com/abenable/student-pa.git"
    echo "     cd student-pa && $COMPOSE_CMD up -d --build"
    exit 1
fi

echo -e "${GREEN}✓ Image pulled${NC}"
echo ""
echo -e "${BLUE}Starting Student-PA container...${NC}"

$COMPOSE_CMD up -d

# ─── Health Check ─────────────────────────────────────────────────

echo ""
echo -e "${BLUE}Waiting for container to be healthy...${NC}"

for i in {1..30}; do
    STATUS=$(docker inspect --format='{{.State.Health.Status}}' "$CONTAINER_NAME" 2>/dev/null || echo "starting")
    if [ "$STATUS" = "healthy" ]; then
        echo -e "${GREEN}✓ Container is healthy${NC}"
        break
    elif [ "$STATUS" = "unhealthy" ]; then
        echo -e "${RED}✗ Container became unhealthy${NC}"
        echo "   Check logs: docker logs -f $CONTAINER_NAME"
        exit 1
    fi
    echo -n "."
    sleep 1
done

if [ "$STATUS" != "healthy" ]; then
    echo ""
    echo -e "${YELLOW}⚠ Container did not become healthy within 30s.${NC}"
    echo "   Check logs: docker logs -f $CONTAINER_NAME"
fi

echo ""
echo -e "${GREEN}=========================================${NC}"
echo -e "${GREEN}  Student-PA is running!${NC}"
echo -e "${GREEN}=========================================${NC}"
echo ""
echo "  Container:  $CONTAINER_NAME"
echo "  Directory:  $INSTALL_DIR"
echo ""
echo "Quick commands:"
echo "  docker logs -f $CONTAINER_NAME        # View logs"
echo "  docker exec -it $CONTAINER_NAME hermes setup   # First-time setup"
echo "  docker exec -it $CONTAINER_NAME hermes         # Interactive chat"
echo "  docker exec -it $CONTAINER_NAME hermes -z \"Your prompt\"  # One-shot"
echo ""

if [ -n "${TELEGRAM_BOT_TOKEN:-}" ]; then
    echo "Telegram gateway:"
    echo "  docker exec -d $CONTAINER_NAME hermes gateway run"
    echo ""
fi

echo -e "${YELLOW}Next steps:${NC}"
echo "  1. Run first-time setup:  docker exec -it $CONTAINER_NAME hermes setup"
echo "  2. Configure your model:  docker exec -it $CONTAINER_NAME hermes model"
if [ -n "${TELEGRAM_BOT_TOKEN:-}" ]; then
    echo "  3. Start Telegram bot:    docker exec -d $CONTAINER_NAME hermes gateway run"
fi
echo ""
