#!/usr/bin/env bash
#
# Student-PA One-Line Installer
# Usage: curl -fsSL https://raw.githubusercontent.com/abenable/student-pa/main/install.sh | bash
#        curl -fsSL ... | bash -s -- --non-interactive
#

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Config
INSTALL_DIR="${HOME}/student-pa"
IMAGE_NAME="ghcr.io/abenable/student-pa:latest"
CONTAINER_NAME="student-pa-agent"

# Docker Compose detection
if docker compose version &>/dev/null; then
    COMPOSE_CMD="docker compose"
elif docker-compose version &>/dev/null; then
    COMPOSE_CMD="docker-compose"
else
    COMPOSE_CMD=""
fi

echo -e "${BLUE}=========================================${NC}"
echo -e "${BLUE}  Student-PA Installer${NC}"
echo -e "${BLUE}  Hermes Agent for Students${NC}"
echo -e "${BLUE}=========================================${NC}"
echo ""

# ─── Check Prerequisites ──────────────────────────────────────────

check_command() {
    if ! command -v "$1" &> /dev/null; then
        echo -e "${RED}✗ $1 is not installed.${NC}"
        return 1
    fi
    echo -e "${GREEN}✓ $1 found${NC}"
}

echo -e "${BLUE}Checking prerequisites...${NC}"

MISSING_DEPS=0
check_command "docker" || MISSING_DEPS=1
check_command "curl" || MISSING_DEPS=1

if [ -z "$COMPOSE_CMD" ]; then
    echo -e "${RED}✗ Docker Compose is not installed.${NC}"
    MISSING_DEPS=1
else
    echo -e "${GREEN}✓ Docker Compose found ($COMPOSE_CMD)${NC}"
fi

if [ "$MISSING_DEPS" -eq 1 ]; then
    echo ""
    echo -e "${RED}Please install the missing dependencies and re-run.${NC}"
    echo "  Docker:         https://docs.docker.com/get-docker/"
    echo "  Docker Compose: sudo apt-get install docker-compose-plugin"
    exit 1
fi

if ! docker info &> /dev/null; then
    echo -e "${RED}✗ Docker daemon is not running.${NC}"
    echo "   Start Docker:  sudo systemctl start docker"
    exit 1
fi

echo ""

# ─── Collect Configuration ────────────────────────────────────────

NON_INT=false
if [ "${1:-}" = "--non-interactive" ] || [ "${NON_INTERACTIVE:-}" = "true" ]; then
    NON_INT=true
fi

prompt_or_env() {
    local var_name="$1"
    local prompt_text="$2"
    local is_secret="${3:-false}"
    local value=""

    eval "value=\"\${$var_name:-}\""

    if [ -n "$value" ]; then
        echo -e "${GREEN}✓ $var_name is set from environment${NC}"
        return
    fi

    if [ "$NON_INT" = true ]; then
        echo -e "${RED}✗ $var_name is required but not set.${NC}"
        echo "   Set it via environment variable: export $var_name=..."
        exit 1
    fi

    echo -n "$prompt_text: "
    if [ "$is_secret" = true ]; then
        read -rs value
        echo ""
    else
        read -r value
    fi

    if [ -z "$value" ]; then
        echo -e "${YELLOW}⚠ $var_name is empty. Some features may not work.${NC}"
    fi

    eval "export $var_name=\"$value\""
}

random_hex() {
    local bytes="${1:-32}"

    if command -v openssl &> /dev/null; then
        openssl rand -hex "$bytes"
    else
        od -An -N "$bytes" -tx1 /dev/urandom | tr -d ' \n'
    fi
}

echo -e "${BLUE}Configuring Student-PA...${NC}"
echo "   LiteLLM endpoint: https://litellm.byte10x.dev (hardcoded)"
echo "   (Set vars as environment variables to skip prompts)"
echo ""

prompt_or_env "LITELLM_ADMIN_KEY" "LiteLLM Admin Key (for creating per-student keys)" "true"
prompt_or_env "SIGNUP_BOT_TOKEN" "Signup Bot Token from @BotFather" "true"
prompt_or_env "PROVISIONER_SECRET" "Provisioner shared secret (any random string)" "true"
prompt_or_env "DATABASE_URL" "Existing PostgreSQL DATABASE_URL" "true"
prompt_or_env "TELEGRAM_API_ID" "Telegram API ID (from my.telegram.org/apps)" "false"
prompt_or_env "TELEGRAM_API_HASH" "Telegram API Hash (from my.telegram.org/apps)" "true"

if [ "${USE_LOCAL_AGENT_IMAGE:-false}" = "true" ]; then
    IMAGE_NAME="student-pa-agent:latest"
fi

WEB_PORT="${WEB_PORT:-3000}"
BETTER_AUTH_URL="${BETTER_AUTH_URL:-http://localhost:${WEB_PORT}}"
BETTER_AUTH_SECRET="${BETTER_AUTH_SECRET:-$(random_hex 32)}"
WORKER_URL="${WORKER_URL:-http://worker:8000}"
AGENTS_BASE_DIR="${AGENTS_BASE_DIR:-/agents}"
AGENTS_HOST_BASE_DIR="${AGENTS_HOST_BASE_DIR:-$INSTALL_DIR/agents}"
AGENT_DOCKER_NETWORK="${AGENT_DOCKER_NETWORK:-student-pa}"
TELEGRAM_SESSION="${TELEGRAM_SESSION:-/data/botfather_session}"
PROVISION_RETRIES="${PROVISION_RETRIES:-3}"
PROVISION_RETRY_DELAY_SECONDS="${PROVISION_RETRY_DELAY_SECONDS:-10}"

# ─── Setup Directory & Config ─────────────────────────────────────

echo ""
echo -e "${BLUE}Setting up installation directory...${NC}"

mkdir -p "$INSTALL_DIR"/{hermes-data,student-data,agents}
cd "$INSTALL_DIR"

cat > .env <<EOF
# Student-PA Environment Configuration
# Generated by installer on $(date -Iseconds)

# Existing database server
DATABASE_URL=${DATABASE_URL}

# Web / Auth
BETTER_AUTH_URL=${BETTER_AUTH_URL}
BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
WEB_PORT=${WEB_PORT}
WORKER_URL=${WORKER_URL}

# LiteLLM Gateway (hardcoded in worker)
LITELLM_ADMIN_KEY=${LITELLM_ADMIN_KEY:-}
DEFAULT_MODEL=${DEFAULT_MODEL:-Mythos}

# Provisioner
SIGNUP_BOT_TOKEN=${SIGNUP_BOT_TOKEN:-}
PROVISIONER_SECRET=${PROVISIONER_SECRET:-}
AGENT_IMAGE=${IMAGE_NAME}
AGENTS_BASE_DIR=${AGENTS_BASE_DIR}
AGENTS_HOST_BASE_DIR=${AGENTS_HOST_BASE_DIR}
AGENT_DOCKER_NETWORK=${AGENT_DOCKER_NETWORK}
PROVISION_RETRIES=${PROVISION_RETRIES}
PROVISION_RETRY_DELAY_SECONDS=${PROVISION_RETRY_DELAY_SECONDS}

# Telethon (BotFather automation)
TELEGRAM_API_ID=${TELEGRAM_API_ID:-}
TELEGRAM_API_HASH=${TELEGRAM_API_HASH:-}
TELEGRAM_SESSION=${TELEGRAM_SESSION}

# Template agent Telegram gateway (optional single-student mode)
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
TELEGRAM_ALLOWED_USERS=${TELEGRAM_ALLOWED_USERS:-}
TELEGRAM_HOME_CHANNEL=${TELEGRAM_HOME_CHANNEL:-}
EOF

echo -e "${GREEN}✓ Configuration written to $INSTALL_DIR/.env${NC}"

# ─── First-run: Telethon session auth ─────────────────────────────

if [ -z "${SKIP_TELETHON_AUTH:-}" ]; then
    echo ""
    echo -e "${YELLOW}Telethon session setup (needed for BotFather automation)${NC}"
    echo "   This will prompt you to log in with your Telegram account once."
    echo "   The session is saved to a Docker volume and reused on restarts."
    echo "   Skip this step with: export SKIP_TELETHON_AUTH=1 if you already copied a valid session to ./worker/sessions/botfather_session."
    echo ""
    echo "   Run after containers are up:"
    echo "     $COMPOSE_CMD run --rm worker python -c \""
    echo "       from telethon.sync import TelegramClient; \""
    echo "       c = TelegramClient('/data/botfather_session', $TELEGRAM_API_ID, '$TELEGRAM_API_HASH'); \""
    echo "       c.start(); print('Session saved')\""
fi

# ─── Pull & Run ───────────────────────────────────────────────────

echo ""
echo -e "${BLUE}Starting Student-PA services...${NC}"

if [ "$IMAGE_NAME" = "student-pa-agent:latest" ]; then
    echo -e "${BLUE}  → Building local agent image...${NC}"
    docker build -t "$IMAGE_NAME" ./agent
else
    echo -e "${BLUE}  → Checking agent image access...${NC}"
    if ! docker manifest inspect "$IMAGE_NAME" >/dev/null 2>&1; then
        echo -e "${YELLOW}⚠ Cannot access $IMAGE_NAME from Docker.${NC}"
        echo "   If the GHCR package is private, log in first:"
        echo "     echo '<PAT_WITH_READ_PACKAGES>' | docker login ghcr.io -u '<github-user>' --password-stdin"
        echo "   Or build locally instead:"
        echo "     curl -fsSL https://raw.githubusercontent.com/abenable/student-pa/main/install.sh | USE_LOCAL_AGENT_IMAGE=true bash"
        exit 1
    fi
fi

# Start backend (signup bot + provisioner)
echo -e "${BLUE}  → Starting backend...${NC}"
$COMPOSE_CMD up -d --build worker

# Optionally start template agent for single-student mode
if [ "${START_TEMPLATE_AGENT:-false}" = "true" ]; then
    echo -e "${BLUE}  → Starting template agent...${NC}"
    $COMPOSE_CMD -f agent/docker-compose.yml up -d --build
fi

echo ""
echo -e "${GREEN}=========================================${NC}"
echo -e "${GREEN}  Student-PA is running!${NC}"
echo -e "${GREEN}=========================================${NC}"
echo ""
echo "  Directory:  $INSTALL_DIR"
echo "  Agents dir: $INSTALL_DIR/agents/"
echo ""
echo "Services:"
echo "  Backend:     $COMPOSE_CMD logs -f worker"
if [ "${START_TEMPLATE_AGENT:-false}" = "true" ]; then
    echo "  Template:    $COMPOSE_CMD -f agent/docker-compose.yml logs -f"
fi
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo "  1. Authenticate Telethon (see instructions above) if not done"
echo "  2. DM your signup bot to provision a student agent"
echo "  3. Each student gets their own Telegram bot + isolated container"
echo "  4. Optional: Start template agent with:"
echo "     START_TEMPLATE_AGENT=true $COMPOSE_CMD -f agent/docker-compose.yml up -d --build"
echo ""
