/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardProvisionRouteImport } from './routes/dashboard/provision'
import { Route as DashboardProductsRouteImport } from './routes/dashboard/products'
import { Route as DashboardOnboardingRouteImport } from './routes/dashboard/onboarding'
import { Route as DashboardChatRouteImport } from './routes/dashboard/chat'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as ApiReferralRouteImport } from './routes/api/referral'
import { Route as ApiProvisionRouteImport } from './routes/api/provision'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as DashboardProductsServiceIdRouteImport } from './routes/dashboard/products.$serviceId'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard/admin.users'
import { Route as DashboardAdminAgentsRouteImport } from './routes/dashboard/admin.agents'
import { Route as ApiProvisionStatusRouteImport } from './routes/api/provision.status'
import { Route as ApiProvisionResumeRouteImport } from './routes/api/provision.resume'
import { Route as ApiOnboardingSkipRouteImport } from './routes/api/onboarding.skip'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAdminApprovalsRouteImport } from './routes/api/admin/approvals'
import { Route as ApiAdminAgentsRouteImport } from './routes/api/admin/agents'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProvisionRoute = DashboardProvisionRouteImport.update({
  id: '/provision',
  path: '/provision',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsRoute = DashboardProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOnboardingRoute = DashboardOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChatRoute = DashboardChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiReferralRoute = ApiReferralRouteImport.update({
  id: '/api/referral',
  path: '/api/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProvisionRoute = ApiProvisionRouteImport.update({
  id: '/api/provision',
  path: '/api/provision',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProductsServiceIdRoute =
  DashboardProductsServiceIdRouteImport.update({
    id: '/$serviceId',
    path: '/$serviceId',
    getParentRoute: () => DashboardProductsRoute,
  } as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminAgentsRoute = DashboardAdminAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const ApiProvisionStatusRoute = ApiProvisionStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiProvisionRoute,
} as any)
const ApiProvisionResumeRoute = ApiProvisionResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => ApiProvisionRoute,
} as any)
const ApiOnboardingSkipRoute = ApiOnboardingSkipRouteImport.update({
  id: '/api/onboarding/skip',
  path: '/api/onboarding/skip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminApprovalsRoute = ApiAdminApprovalsRouteImport.update({
  id: '/api/admin/approvals',
  path: '/api/admin/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAgentsRoute = ApiAdminAgentsRouteImport.update({
  id: '/api/admin/agents',
  path: '/api/admin/agents',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/provision': typeof ApiProvisionRouteWithChildren
  '/api/referral': typeof ApiReferralRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/onboarding': typeof DashboardOnboardingRoute
  '/dashboard/products': typeof DashboardProductsRouteWithChildren
  '/dashboard/provision': typeof DashboardProvisionRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/admin/agents': typeof ApiAdminAgentsRoute
  '/api/admin/approvals': typeof ApiAdminApprovalsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/onboarding/skip': typeof ApiOnboardingSkipRoute
  '/api/provision/resume': typeof ApiProvisionResumeRoute
  '/api/provision/status': typeof ApiProvisionStatusRoute
  '/dashboard/admin/agents': typeof DashboardAdminAgentsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/products/$serviceId': typeof DashboardProductsServiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/provision': typeof ApiProvisionRouteWithChildren
  '/api/referral': typeof ApiReferralRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/onboarding': typeof DashboardOnboardingRoute
  '/dashboard/products': typeof DashboardProductsRouteWithChildren
  '/dashboard/provision': typeof DashboardProvisionRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/admin/agents': typeof ApiAdminAgentsRoute
  '/api/admin/approvals': typeof ApiAdminApprovalsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/onboarding/skip': typeof ApiOnboardingSkipRoute
  '/api/provision/resume': typeof ApiProvisionResumeRoute
  '/api/provision/status': typeof ApiProvisionStatusRoute
  '/dashboard/admin/agents': typeof DashboardAdminAgentsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/products/$serviceId': typeof DashboardProductsServiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/provision': typeof ApiProvisionRouteWithChildren
  '/api/referral': typeof ApiReferralRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/onboarding': typeof DashboardOnboardingRoute
  '/dashboard/products': typeof DashboardProductsRouteWithChildren
  '/dashboard/provision': typeof DashboardProvisionRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/admin/agents': typeof ApiAdminAgentsRoute
  '/api/admin/approvals': typeof ApiAdminApprovalsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/onboarding/skip': typeof ApiOnboardingSkipRoute
  '/api/provision/resume': typeof ApiProvisionResumeRoute
  '/api/provision/status': typeof ApiProvisionStatusRoute
  '/dashboard/admin/agents': typeof DashboardAdminAgentsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/products/$serviceId': typeof DashboardProductsServiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/services'
    | '/support'
    | '/terms'
    | '/api/chat'
    | '/api/provision'
    | '/api/referral'
    | '/dashboard/admin'
    | '/dashboard/chat'
    | '/dashboard/onboarding'
    | '/dashboard/products'
    | '/dashboard/provision'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/admin/agents'
    | '/api/admin/approvals'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/onboarding/skip'
    | '/api/provision/resume'
    | '/api/provision/status'
    | '/dashboard/admin/agents'
    | '/dashboard/admin/users'
    | '/dashboard/products/$serviceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/services'
    | '/support'
    | '/terms'
    | '/api/chat'
    | '/api/provision'
    | '/api/referral'
    | '/dashboard/admin'
    | '/dashboard/chat'
    | '/dashboard/onboarding'
    | '/dashboard/products'
    | '/dashboard/provision'
    | '/dashboard/settings'
    | '/dashboard'
    | '/api/admin/agents'
    | '/api/admin/approvals'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/onboarding/skip'
    | '/api/provision/resume'
    | '/api/provision/status'
    | '/dashboard/admin/agents'
    | '/dashboard/admin/users'
    | '/dashboard/products/$serviceId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/services'
    | '/support'
    | '/terms'
    | '/api/chat'
    | '/api/provision'
    | '/api/referral'
    | '/dashboard/admin'
    | '/dashboard/chat'
    | '/dashboard/onboarding'
    | '/dashboard/products'
    | '/dashboard/provision'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/admin/agents'
    | '/api/admin/approvals'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/onboarding/skip'
    | '/api/provision/resume'
    | '/api/provision/status'
    | '/dashboard/admin/agents'
    | '/dashboard/admin/users'
    | '/dashboard/products/$serviceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiProvisionRoute: typeof ApiProvisionRouteWithChildren
  ApiReferralRoute: typeof ApiReferralRoute
  ApiAdminAgentsRoute: typeof ApiAdminAgentsRoute
  ApiAdminApprovalsRoute: typeof ApiAdminApprovalsRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOnboardingSkipRoute: typeof ApiOnboardingSkipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/provision': {
      id: '/dashboard/provision'
      path: '/provision'
      fullPath: '/dashboard/provision'
      preLoaderRoute: typeof DashboardProvisionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products': {
      id: '/dashboard/products'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/onboarding': {
      id: '/dashboard/onboarding'
      path: '/onboarding'
      fullPath: '/dashboard/onboarding'
      preLoaderRoute: typeof DashboardOnboardingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/chat': {
      id: '/dashboard/chat'
      path: '/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof DashboardChatRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/referral': {
      id: '/api/referral'
      path: '/api/referral'
      fullPath: '/api/referral'
      preLoaderRoute: typeof ApiReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/provision': {
      id: '/api/provision'
      path: '/api/provision'
      fullPath: '/api/provision'
      preLoaderRoute: typeof ApiProvisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/products/$serviceId': {
      id: '/dashboard/products/$serviceId'
      path: '/$serviceId'
      fullPath: '/dashboard/products/$serviceId'
      preLoaderRoute: typeof DashboardProductsServiceIdRouteImport
      parentRoute: typeof DashboardProductsRoute
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/agents': {
      id: '/dashboard/admin/agents'
      path: '/agents'
      fullPath: '/dashboard/admin/agents'
      preLoaderRoute: typeof DashboardAdminAgentsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/api/provision/status': {
      id: '/api/provision/status'
      path: '/status'
      fullPath: '/api/provision/status'
      preLoaderRoute: typeof ApiProvisionStatusRouteImport
      parentRoute: typeof ApiProvisionRoute
    }
    '/api/provision/resume': {
      id: '/api/provision/resume'
      path: '/resume'
      fullPath: '/api/provision/resume'
      preLoaderRoute: typeof ApiProvisionResumeRouteImport
      parentRoute: typeof ApiProvisionRoute
    }
    '/api/onboarding/skip': {
      id: '/api/onboarding/skip'
      path: '/api/onboarding/skip'
      fullPath: '/api/onboarding/skip'
      preLoaderRoute: typeof ApiOnboardingSkipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/approvals': {
      id: '/api/admin/approvals'
      path: '/api/admin/approvals'
      fullPath: '/api/admin/approvals'
      preLoaderRoute: typeof ApiAdminApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/agents': {
      id: '/api/admin/agents'
      path: '/api/admin/agents'
      fullPath: '/api/admin/agents'
      preLoaderRoute: typeof ApiAdminAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminAgentsRoute: typeof DashboardAdminAgentsRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminAgentsRoute: DashboardAdminAgentsRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardProductsRouteChildren {
  DashboardProductsServiceIdRoute: typeof DashboardProductsServiceIdRoute
}

const DashboardProductsRouteChildren: DashboardProductsRouteChildren = {
  DashboardProductsServiceIdRoute: DashboardProductsServiceIdRoute,
}

const DashboardProductsRouteWithChildren =
  DashboardProductsRoute._addFileChildren(DashboardProductsRouteChildren)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardChatRoute: typeof DashboardChatRoute
  DashboardOnboardingRoute: typeof DashboardOnboardingRoute
  DashboardProductsRoute: typeof DashboardProductsRouteWithChildren
  DashboardProvisionRoute: typeof DashboardProvisionRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardChatRoute: DashboardChatRoute,
  DashboardOnboardingRoute: DashboardOnboardingRoute,
  DashboardProductsRoute: DashboardProductsRouteWithChildren,
  DashboardProvisionRoute: DashboardProvisionRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ApiProvisionRouteChildren {
  ApiProvisionResumeRoute: typeof ApiProvisionResumeRoute
  ApiProvisionStatusRoute: typeof ApiProvisionStatusRoute
}

const ApiProvisionRouteChildren: ApiProvisionRouteChildren = {
  ApiProvisionResumeRoute: ApiProvisionResumeRoute,
  ApiProvisionStatusRoute: ApiProvisionStatusRoute,
}

const ApiProvisionRouteWithChildren = ApiProvisionRoute._addFileChildren(
  ApiProvisionRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiProvisionRoute: ApiProvisionRouteWithChildren,
  ApiReferralRoute: ApiReferralRoute,
  ApiAdminAgentsRoute: ApiAdminAgentsRoute,
  ApiAdminApprovalsRoute: ApiAdminApprovalsRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOnboardingSkipRoute: ApiOnboardingSkipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
