/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardServicesRouteImport } from './routes/dashboard/services'
import { Route as DashboardProvisionRouteImport } from './routes/dashboard/provision'
import { Route as DashboardOnboardingRouteImport } from './routes/dashboard/onboarding'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as ApiReferralRouteImport } from './routes/api/referral'
import { Route as ApiProvisionRouteImport } from './routes/api/provision'
import { Route as DashboardServicesServiceIdRouteImport } from './routes/dashboard/services.$serviceId'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard/admin.users'
import { Route as DashboardAdminAgentsRouteImport } from './routes/dashboard/admin.agents'
import { Route as ApiOnboardingSkipRouteImport } from './routes/api/onboarding.skip'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServicesRoute = DashboardServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProvisionRoute = DashboardProvisionRouteImport.update({
  id: '/provision',
  path: '/provision',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOnboardingRoute = DashboardOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiReferralRoute = ApiReferralRouteImport.update({
  id: '/api/referral',
  path: '/api/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProvisionRoute = ApiProvisionRouteImport.update({
  id: '/api/provision',
  path: '/api/provision',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardServicesServiceIdRoute =
  DashboardServicesServiceIdRouteImport.update({
    id: '/$serviceId',
    path: '/$serviceId',
    getParentRoute: () => DashboardServicesRoute,
  } as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminAgentsRoute = DashboardAdminAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const ApiOnboardingSkipRoute = ApiOnboardingSkipRouteImport.update({
  id: '/api/onboarding/skip',
  path: '/api/onboarding/skip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/provision': typeof ApiProvisionRoute
  '/api/referral': typeof ApiReferralRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/onboarding': typeof DashboardOnboardingRoute
  '/dashboard/provision': typeof DashboardProvisionRoute
  '/dashboard/services': typeof DashboardServicesRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/onboarding/skip': typeof ApiOnboardingSkipRoute
  '/dashboard/admin/agents': typeof DashboardAdminAgentsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/services/$serviceId': typeof DashboardServicesServiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/provision': typeof ApiProvisionRoute
  '/api/referral': typeof ApiReferralRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/onboarding': typeof DashboardOnboardingRoute
  '/dashboard/provision': typeof DashboardProvisionRoute
  '/dashboard/services': typeof DashboardServicesRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/onboarding/skip': typeof ApiOnboardingSkipRoute
  '/dashboard/admin/agents': typeof DashboardAdminAgentsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/services/$serviceId': typeof DashboardServicesServiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/provision': typeof ApiProvisionRoute
  '/api/referral': typeof ApiReferralRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/onboarding': typeof DashboardOnboardingRoute
  '/dashboard/provision': typeof DashboardProvisionRoute
  '/dashboard/services': typeof DashboardServicesRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/onboarding/skip': typeof ApiOnboardingSkipRoute
  '/dashboard/admin/agents': typeof DashboardAdminAgentsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/services/$serviceId': typeof DashboardServicesServiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/api/provision'
    | '/api/referral'
    | '/dashboard/admin'
    | '/dashboard/onboarding'
    | '/dashboard/provision'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/onboarding/skip'
    | '/dashboard/admin/agents'
    | '/dashboard/admin/users'
    | '/dashboard/services/$serviceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/api/provision'
    | '/api/referral'
    | '/dashboard/admin'
    | '/dashboard/onboarding'
    | '/dashboard/provision'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/onboarding/skip'
    | '/dashboard/admin/agents'
    | '/dashboard/admin/users'
    | '/dashboard/services/$serviceId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/api/provision'
    | '/api/referral'
    | '/dashboard/admin'
    | '/dashboard/onboarding'
    | '/dashboard/provision'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/onboarding/skip'
    | '/dashboard/admin/agents'
    | '/dashboard/admin/users'
    | '/dashboard/services/$serviceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiProvisionRoute: typeof ApiProvisionRoute
  ApiReferralRoute: typeof ApiReferralRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOnboardingSkipRoute: typeof ApiOnboardingSkipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/services': {
      id: '/dashboard/services'
      path: '/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof DashboardServicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/provision': {
      id: '/dashboard/provision'
      path: '/provision'
      fullPath: '/dashboard/provision'
      preLoaderRoute: typeof DashboardProvisionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/onboarding': {
      id: '/dashboard/onboarding'
      path: '/onboarding'
      fullPath: '/dashboard/onboarding'
      preLoaderRoute: typeof DashboardOnboardingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/referral': {
      id: '/api/referral'
      path: '/api/referral'
      fullPath: '/api/referral'
      preLoaderRoute: typeof ApiReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/provision': {
      id: '/api/provision'
      path: '/api/provision'
      fullPath: '/api/provision'
      preLoaderRoute: typeof ApiProvisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/services/$serviceId': {
      id: '/dashboard/services/$serviceId'
      path: '/$serviceId'
      fullPath: '/dashboard/services/$serviceId'
      preLoaderRoute: typeof DashboardServicesServiceIdRouteImport
      parentRoute: typeof DashboardServicesRoute
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/agents': {
      id: '/dashboard/admin/agents'
      path: '/agents'
      fullPath: '/dashboard/admin/agents'
      preLoaderRoute: typeof DashboardAdminAgentsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/api/onboarding/skip': {
      id: '/api/onboarding/skip'
      path: '/api/onboarding/skip'
      fullPath: '/api/onboarding/skip'
      preLoaderRoute: typeof ApiOnboardingSkipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminAgentsRoute: typeof DashboardAdminAgentsRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminAgentsRoute: DashboardAdminAgentsRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardServicesRouteChildren {
  DashboardServicesServiceIdRoute: typeof DashboardServicesServiceIdRoute
}

const DashboardServicesRouteChildren: DashboardServicesRouteChildren = {
  DashboardServicesServiceIdRoute: DashboardServicesServiceIdRoute,
}

const DashboardServicesRouteWithChildren =
  DashboardServicesRoute._addFileChildren(DashboardServicesRouteChildren)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardOnboardingRoute: typeof DashboardOnboardingRoute
  DashboardProvisionRoute: typeof DashboardProvisionRoute
  DashboardServicesRoute: typeof DashboardServicesRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardOnboardingRoute: DashboardOnboardingRoute,
  DashboardProvisionRoute: DashboardProvisionRoute,
  DashboardServicesRoute: DashboardServicesRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiProvisionRoute: ApiProvisionRoute,
  ApiReferralRoute: ApiReferralRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOnboardingSkipRoute: ApiOnboardingSkipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
